const data = [
  {
    call_id: "2ef23bef-fea8-43d6-98c3-5a39757996b9",
    start_time: "2024-10-07T17:34:53.404Z",
    end_time: "2024-10-07T17:35:11.426Z",
    call_duration: 18,
    call_status: "ended",
    ended_reason: "customer-ended-call",
    total_cost: 0.02,
    cost_breakdown_transport: 0.0,
    cost_breakdown_stt: 0.0,
    cost_breakdown_llm: 0.0,
    cost_breakdown_tts: 0.0,
    call_summary: "Luke from Nissan Motors Malta called Sahil to remind him about an upcoming service appointment for his Micra, scheduled for October 8th at 5 PM. Luke asked if Sahil could still make the appointment and was prepared to offer rescheduling options if needed.",
    transcript: "AI: Hello, this is Luke calling from Nissan Motors Malta. Am I speaking with Sahil? Appointment Reminder: Great. I'm calling to remind you about your upcoming service appointment for your Micra. It's scheduled for 8th October at 5 PM. Are you still able to make it? Confirmation Handling: - If yes: Excellent. We look forward to seeing you then. Do you have any questions or additional notes for our service team? - If no: I understand. Would you like to reschedule for a more convenient time? Rescheduling (if necessary): No problem at all. Let me check our available slots. How about [alternative date and time]? Additional Information: Before we wrap up, is there anything else you'd like us to know about your vehicle or the service you're expecting? Closing: Thank you for choosing Nissan Motors Malta. We appreciate your business and look forward to serving you. Have a great day! Handling Common Scenarios: - Customer Has Questions: Listen attentively, provide clear, concise answers if possible. If unsure, offer to have a service representative call back. - Customer Wants to Cancel: Express understanding, ask if they'd like to reschedule. If not, politely inquire about the reason for feedback and thank them for their time. - Customer Has Additional Requests: Note specific requests or concerns, assure the customer that information will be passed to the service team, and offer a technician call back if needed. Unable to Reach Customer: If unable to reach after two attempts, leave a voicemail: Hello, this is Luke from Nissan Motors Malta. I'm calling to remind you of your service appointment scheduled for [Date] at [Time]. If you need to make any changes, please call us back at +356 2596 9999. We look forward to seeing you. Thank you. Hello. This is Luke calling from Nissan Motors Malta. Am I speaking with Sawhill?",
    avg_cost_per_minute: 0.0,
    recording_url: "https://auth.vapi.ai/storage/v1/object/public/recordings/2ef23bef-fea8-43d6-98c3-5a39757996b9-1728322513933-8805f197-9dd7-4e51-9b78-ea6a8522bb02-mono.wav",
    cumulative_total_cost: 55.03,
    week_number: 41,
    phone_number: null
  },
  {
    call_id: "8dcfe75d-2730-4d52-afb0-4063585110cf",
    start_time: null,
    end_time: null,
    call_duration: null,
    call_status: "ended",
    ended_reason: "customer-did-not-answer",
    total_cost: 0.0,
    cost_breakdown_transport: 0.0,
    cost_breakdown_stt: 0.0,
    cost_breakdown_llm: 0.0,
    cost_breakdown_tts: 0.0,
    call_summary: "",
    transcript: "",
    avg_cost_per_minute: 0.0,
    recording_url: null,
    cumulative_total_cost: 0.0,
    week_number: null,
    phone_number: null
  },
  {
    call_id: "82925761-580e-4945-83b4-32f0d99025ea",
    start_time: "2024-10-07T17:33:45.675Z",
    end_time: "2024-10-07T17:34:07.860Z",
    call_duration: 22,
    call_status: "ended",
    ended_reason: "customer-ended-call",
    total_cost: 0.02,
    cost_breakdown_transport: 0.0,
    cost_breakdown_stt: 0.0,
    cost_breakdown_llm: 0.0,
    cost_breakdown_tts: 0.0,
    call_summary: "Luke from Nissan Motors Malta called Sahil to remind him of an upcoming service appointment for his Micra on October 8th at 5 PM. Luke confirmed Sahil's ability to attend the scheduled appointment.",
    transcript: "AI: Hello, this is Luke calling from Nissan Motors Malta. Am I speaking with Sahil? User: Oh, yes. AI: Great. Sajal. I'm calling to remind you about your upcoming service appointment for your Micra. It's scheduled for the eighth of October at 5 PM. Are you still able to make it?",
    avg_cost_per_minute: 0.0,
    recording_url: "https://auth.vapi.ai/storage/v1/object/public/recordings/82925761-580e-4945-83b4-32f0d99025ea-1728322450368-4b4a9ae2-eec3-44cc-a4b2-061470373a84-mono.wav",
    cumulative_total_cost: 55.01,
    week_number: 41,
    phone_number: null
  },
  {
    call_id: "e038014e-55c9-4b85-a9c6-15d71ba3b55a",
    start_time: null,
    end_time: null,
    call_duration: null,
    call_status: "ended",
    ended_reason: "customer-did-not-answer",
    total_cost: 0.0,
    cost_breakdown_transport: 0.0,
    cost_breakdown_stt: 0.0,
    cost_breakdown_llm: 0.0,
    cost_breakdown_tts: 0.0,
    call_summary: "",
    transcript: "",
    avg_cost_per_minute: 0.0,
    recording_url: null,
    cumulative_total_cost: 0.0,
    week_number: null,
    phone_number: null
  },
  {
    call_id: "385a26ce-48bc-46d8-8505-23294c790b07",
    start_time: "2024-10-07T15:35:26.740Z",
    end_time: "2024-10-07T15:37:53.846Z",
    call_duration: 147,
    call_status: "ended",
    ended_reason: "assistant-ended-call",
    total_cost: 0.15,
    cost_breakdown_transport: 0.0,
    cost_breakdown_stt: 0.03,
    cost_breakdown_llm: 0.0,
    cost_breakdown_tts: 0.0,
    call_summary: "Here's a 2-3 sentence summary of the transcript: John Smith called to book a classic room at the Intercontinental London O2 for one night on the 8th of the current month, with access to spa facilities. Riley, the front desk support, confirmed the booking for a total of 242 pounds including VAT. John declined to provide an email address for confirmation details but completed the reservation.",
    transcript: "AI: Thank you for calling Intercontinental London the o 2. This is Riley. How may I assist you today? User: Hi, Riley. Let's be quick. I want to book a room. It's gonna be a classic room. My dates are on the eighth of It's gonna be for 1 night. I have a special request for a spa. And, uh, yeah, that's it. AI: I'd be delighted to help you with that. Just to confirm, you're looking to book a classic room for 1 night starting from the eighth of this month? Regarding your special request for the spa, would you like to book? A specific treatment or just access to the facilities. Once I have that information, I can provide you with the total cost for your stay. User: Sure. I just need access to that, and my name is John Smith. I will be staying for 1 night only. And, yes, I need the classroom. AI: Thank you, John. AI: I will go ahead and confirm your reservation for a classic room for 1 night. Starting from the eighth of this month. Along with access to the spa facilities, Your total is 242 pounds. Can I have your email address to send you the confirmation details? User: No. That should be it. You know? AI: That's perfectly fine, John. I will proceed with your reservation without an email confirmation. To recap, you have a classic room boot for 1 night starting from the eighth of this month with access to the spa facilities. Thank you for choosing InterContinental London, the o 2. We're looking forward to welcoming you and ensuring you have a wonderful stay with us. If you need anything else, feel free to reach out. Have a great day. User: Yeah. Bye bye. AI: Thank you for calling Intercontinental London the o 2. It's been a pleasure assisting you today. We appreciate your interest in our hotel. And look forward to welcoming you soon. If you need any further assistance, please don't hesitate to call us back. Have a wonderful day.",
    avg_cost_per_minute: 0.0,
    recording_url: "https://auth.vapi.ai/storage/v1/object/public/recordings/385a26ce-48bc-46d8-8505-23294c790b07-1728315476351-7bec576d-75d0-4ef7-b42f-d8831a493e2d-mono.wav",
    cumulative_total_cost: 54.99,
    week_number: 41,
    phone_number: null
  },
  {
    call_id: "cc1936fb-35e0-4858-ba95-9639f7269524",
    start_time: "2024-10-07T15:28:52.897Z",
    end_time: "2024-10-07T15:31:53.070Z",
    call_duration: 180,
    call_status: "ended",
    ended_reason: "assistant-ended-call",
    total_cost: 0.18,
    cost_breakdown_transport: 0.0,
    cost_breakdown_stt: 0.03,
    cost_breakdown_llm: 0.0,
    cost_breakdown_tts: 0.0,
    call_summary: "Here's a summary of the transcript in 2-3 sentences: Sahil called the Intercontinental London the O2 to book a room. He reserved a classic room for one night on the eighth, requested champagne in the room upon arrival, and booked a spa treatment for 4 PM. The total cost for the stay, including VAT, was 242 pounds, and Riley from the front desk confirmed the reservation.",
    transcript: "AI: Thank you for calling Intercontinental London the o 2. This is Riley. How may I assist you today? User: Hi, Riley. This is Sahil here. AI: Hello, Sahil. It's great to hear from you. How can I assist you today? Are you looking to make a room reservation, or do you have any questions about our hotel amenities? User: Yes. I'm looking to get a room book AI: I'd be delighted to help you with a room reservation, Sahil. May I ask when you're planning to stay with us? User: Yes. It is gonna be on the eighth of AI: Thank you for that information, Sahil. Just to confirm, is your stay on the eighth of this month? How many nights will you be staying with us? User: Only the 1 night. AI: Great. So you're looking to stay for 1 night on the eighth, Let me tell you about the beautiful rooms we have available. We offer classic king and twin rooms, which are perfect for a comfortable stay. If you're looking for something with a bit more space and stunning views, our deluxe king rooms are located on the higher floors, and offer breathtaking vistas of the River Thames or the o 2. We also have a classic accessible room designed for guests with mobility needs, as well as luxurious junior suites and 1 bedroom suites for those seeking extra comfort. Which of these options interests you the most? User: Yeah. Sure. So listen. What do I need is I would like to go for the classic room. And it's gonna be, like, an occasion. So I am gonna need some champagne, and I want a spa also booked for me. AI: That sounds wonderful, Sahil. You've chosen the classic room for your special occasion. I can certainly arrange for Champagne to be in your room upon arrival. And I'll also help you book a spa treatment. Let me summarize your booking. You'll be staying in a classic room for 1 night on the eighth, and you'd like champagne and a spa treatment as well. Could you please let me know what time you would like your spa treatment? And if you have any specific preferences for the treatment? User: That should be at 4 PM. That's it. And just get the booking done, please. AI: Perfect. So to summarize, you will be staying in a classic room for 1 night on the eighth. With champagne in your room upon arrival, and a spa treatment booked for 4 PM. The total for your stay will be 242 pounds, which includes VAT. Would you like to go ahead and confirm this reservation? User: Yeah. Sure. AI: Thank you, Sahil. AI: I will go ahead and confirm your reservation. You've booked a classic room for 1 night on the eighth with champagne and a spa treatment at 4 PM. I will finalize this now. Moment, please. Thank you for calling Intercontinental London the o 2. It's been a pleasure assisting you today. We appreciate your interest in our hotel. And look forward to welcoming you soon. If you need any further assistance, please don't hesitate to call us back. Have a wonderful day.",
    avg_cost_per_minute: 0.0,
    recording_url: "https://auth.vapi.ai/storage/v1/object/public/recordings/cc1936fb-35e0-4858-ba95-9639f7269524-1728315115577-9622e871-f707-4cd6-a79d-c280f568e78f-mono.wav",
    cumulative_total_cost: 54.84,
    week_number: 41,
    phone_number: null
  }
];

export default data;
